### ISSUE TITLE
非常棒

### ISSUE THREAD

**Issue by lan202509** [YeYinhai/chrome-lights#1]
不过为什么翻页不放在页尾呢
一般不都是看完一页才考虑翻页？

**Comment by YeYinhai** [comment]
操作便捷，效率更高。
固定位子便于操作，试想1到10页要快速的浏览一遍场景。
（现在你只需把鼠标放到分页上，再鼠标滚动查看内容，从这一页到下一页鼠标只需横向移动一格而已）。
而且内容过滤掉后高度缩短，一屏幕就能容纳70%的内容。
下一页就能重新获取70%的内容，何须再多一个下滚动操作去获取30%的内容呢。
我个人操作习惯是首页滚到底，其他时候直接点下一页下一页，鼠标都不用移动，太爽了。效率大大提高。
